apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: TO_OVERLAY
  labels:
    env: TO_OVERLAY
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: TO_OVERLAY
  source:
    repoURL: https://github.com/wim-vdw/argocd-k8s-resources.git
    targetRevision: main
    path: TO_OVERLAY
  destination:
    name: in-cluster
    namespace: TO_OVERLAY
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.14-3.0/#removing-default-ignores-of-preserveunknownfields-for-crd
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
